# version: '2'

# services:
#   web:
#     build: 
#       context: ./.docker
#       dockerfile: web.docker
    
#     volumes:
#       - ./:/var/www

#     ports:
#       - "8000:80"

#     links:
#       - app

#   app:
#     build: 
#       context: ./.docker
#       dockerfile: app.docker
#     volumes:
#       - ./:/var/www

version: '2'
services:
  app:
    build: .
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE='forge'
      - MYSQL_USER='forge'
      - MYSQL_PASSWORD=''
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''



 